apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-management-service-nginx-config
  namespace: inventory-management-develop
data:
  default.conf: |
    server {
        listen 80;
        server_name sistema-al.com;

        root /var/www/public;
        index index.php index.html;

        # Todas las rutas se envían a index.php
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # PHP-FPM sidecar
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Seguridad: denegar .htaccess y otros archivos ocultos
        location ~ /\. {
            deny all;
        }

        # Logs opcionales
        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;
    }
